source 'https://rubygems.org'

gem 'berkshelf'
gem 'knife-ec2', '~>0.12.0'
gem 'foodcritic', '~>6.0.1'
gem 'chefspec'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'knife-preflight'
gem 'knife-essentials'